
# 配置文件的自动重置设置
# 部分模块的自动加载可能会存在小概率失灵情况
# 用户可根据实际情况自行选择启用与否
# 修改此节点可能需要重新启动服务器才能完全生效
automatic-reload:
  custom-command: false
  dispatcher: false
  handler: false
  listen-mapping: false
  schedule: false
  script-source: false
  script-compiled: false

  action-unicode: false

script-setting:
  # 注释匹配规则
  comment-pattern:
    # 单行注释
    # 匹配 // 及其后所有字符直至换行
    single-line: '(?<!\\)//[^\n]*(?=\n|\r)'
    # 多行注释
    # 匹配 /* 直到 */
    multi-line: '(?<!\\)/\*[^(\*/)]*\*/'

schedule-setting:
  # 指定默认情况下的日期格式
  # yyyy - 年份
  # MM - 月份
  # dd - 当月的天数
  # HH - 二十四小时制
  # hh - 十二小时制
  # mm - 分钟
  # ss - 秒
  date-format: 'yyyy-MM-dd HH:mm:ss'

action-setting:
  unicode:
    special-digit: [ 1, 2, 3, 4, 5, 6, 7, 8, 16, 32, 64, 128 ]

# 调试等级
# off - 关闭
# normal - 普通
# high - 高
# highest - 最高
# monitor - 观察
debug: off